[build-system]
requires = [
    "poetry==1.0.5",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "flower"
version = "0.0.1"
description = "See `README.md`"
license = "Apache-2.0"
authors = [
    "Daniel J. Beutel <daniel@adap.com>",
    "Taner Topal <taner@adap.com>",
]
readme = "README.md"
homepage = "https://github.com/adap/flower"
repository = "https://github.com/adap/flower"
documentation = "https://github.com/adap/flower"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Typing :: Typed",
]
packages = [
    { include = "flower", from = "src" },
]
exclude = [
    "src/**/*_test.py",
]

[tool.poetry.dependencies]
# Mandatory dependencies
python = "==3.7.6"
numpy = "==1.18.1"
grpcio = "==1.27.2"
# Optional dependencies
tensorflow = { version = "==2.1.0", optional = true }

[tool.poetry.extras]
examples-tensorflow = ["tensorflow"]

[tool.poetry.dev-dependencies]
isort = "==4.3.21"
black = "==19.10b0"
mypy = "==0.761"
pylint = "==2.4.4"
pytest = "==5.3.4"
grpcio-tools = "==1.27.2"
mypy-protobuf = "==1.18"
rope = "==0.16.0"
numpy-stubs = { git = "https://github.com/numpy/numpy-stubs.git", rev = "f3c6315738489983f5f37e1477ac68373d71b470" }

[tool.poetry.scripts]
flower-example-server = "flower_examples.tf_mnist_grpc_server:main"
flower-example-client = "flower_examples.tf_mnist_grpc_client:main"

[tool.isort]
line_length = 88
indent = "    "
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.black]
target-version = ['py37']
