name: Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

defaults:
  run:
    working-directory: baselines/flwr_baselines

jobs:
  test_baselines:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.15
      - name: Install build tools
        run: |
          python -m pip install -U pip==23.1.2
          python -m pip install -U setuptools==68.0.0
          python -m pip install -U poetry==1.5.1
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test.sh
