name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U sphinx==2.4.4
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/deploy_docs.sh
