name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  pytorch:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          cd e2e/pytorch
          python -m poetry install
      - name: Cache Datasets
        uses: actions/cache@v2
        with:
          path: "./e2e/pytorch/data"
          key: pytorch-datasets
      - name: Download Datasets
        run: |
          cd e2e/pytorch
          python -c "from torchvision.datasets import CIFAR10; CIFAR10('./data', download=True)"
      - name: Run edge client test
        run: |
          cd e2e/pytorch
          ./test.sh

  tensorflow:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          cd e2e/tensorflow
          python -m poetry install
      - name: Cache Datasets
        uses: actions/cache@v2
        with:
          path: "~/.keras"
          key: keras-datasets
      - name: Download Datasets
        run: |
          python -c "import tensorflow as tf; tf.keras.datasets.cifar10.load_data()"
      - name: Run edge client test
        run: |
          cd e2e/tensorflow
          ./test.sh


  bare:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          cd e2e/bare
          python -m poetry install
      - name: Run edge client test
        run: |
          cd e2e/bare
          ./test.sh

  jax:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.16
      - name: Install
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          cd e2e/jax
          python -m poetry install
      - name: Run edge client test
        run: |
          cd e2e/jax
          ./test.sh
