name: Release

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  nightly_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==21.3.1
          python -m pip install -U setuptools==59.6.0
          python -m pip install -U poetry==1.1.12
      - name: Release nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dev/publish-nightly.sh
