name: Nightly Release

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
      - name: Release nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dev/publish-nightly.sh
