name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_core:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.6.15, 3.7.12, 3.8.12, 3.9.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          sudo apt-get install clang-format-10
          python -m pip install -U pip==21.3.1
          python -m pip install -U setuptools==59.6.0
          python -m pip install -U poetry==1.1.12
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh
