name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_core:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.6.11, 3.7.8, 3.8.3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install
      - name: Check if protos need recompilation
        run: ./dev/check_protos.sh
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test.sh

  test_benchmark:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "benchmark"
          python -m pip install -U tensorflow-cpu==2.2.0
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-benchmark.sh

  test_example_pytorch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "examples-pytorch"
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-example-pytorch.sh

  test_example_tensorflow:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "examples-tensorflow"
          python -m pip install -U tensorflow-cpu==2.2.0
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-example-tensorflow.sh
