name: Build

on:
  push:
    branches:
      - master
    paths:
      - "src/flower_ops/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/flower_ops/**"

jobs:
  test_ops:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.6
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.0.2
          python -m pip install -U setuptools==45.2.0
          python -m pip install -U poetry==1.0.5
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "ops"
          python -m pip install -U tensorflow-cpu==2.1.0
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-ops.sh
