name: Release

on:
  schedule:
    - cron: "0 23 * * *"

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  nightly_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: 3.7.15
          pip-version: 23.1.2
          setuptools-version: 68.0.0
          poetry-version: 1.5.1
      - name: Release nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dev/publish-nightly.sh
