name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test_core:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [3.7.15, 3.8.15, 3.9.16, 3.10.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install -U pip==23.1.2
          python -m pip install -U setuptools==68.0.0
          python -m pip install -U poetry==1.5.1
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --all-extras
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh
