name: Build Tools

on:
  push:
    branches:
      - main
    paths:
      - "src/py/flwr_tool/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/py/flwr_tool/**"

jobs:
  test_tools:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install build tools
        run: |
          python -m pip install -U pip==21.3.1
          python -m pip install -U setuptools==59.6.0
          python -m pip install -U poetry==1.1.12
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-tool.sh
