name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr_title_check:
    runs-on: ubuntu-22.04
    name: Title format
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          poetry-skip: 'true'
      - name: Install dependencies (mandatory only)
        run: python -m pip install PyYAML==6.0.1
      - name: Check PR title format 
        run: python ./dev/check_pr_title.py "${{ github.event.pull_request.title }}"
